### ISSUE TITLE
Post Orlando migration clean-up tasks (Sept/Oct 2020)

### ISSUE THREAD

**Issue by jefferya** [cwrc/cwrc_migration_batch#18]
Group together several tickets describing clean-up tasks

Problems
- [ ] Validation: person entities - https://github.com/cwrc/OrlandoMigration-TestOutputs/issues/26
- [ ] Validation: event - https://github.com/cwrc/OrlandoMigration-TestOutputs/issues/27
- [ ] Bibliograph: blank labels (e.g., cases of a journal part without the journal name) - https://github.com/cwrc/OrlandoMigration-TestOutputs/issues/24

Enhancements
- [ ] Organization publisher URI's: not populated if doesn't match standard Org name - https://github.com/cwrc/OrlandoMigration-TestOutputs/issues/27

Notes:
- Organization schema validation: successful
